#!/bin/bash

javac NoRepeat.java
#test1
java NoRepeat "abcdabd" > output

diff output test1.out
if [ $? -ne 0 ]; then
	echo "test1 failed"
else 
	echo "test1 passed"
fi
#test2
java NoRepeat "bbbb" > output
diff output test2.out
if [ $? -ne 0 ]; then
	echo "test2 failed"
else 
	echo "test2 passed"
fi	

#test3
java NoRepeat "pwwkew" > output
diff output test3.out
if [ $? -ne 0 ]; then
	echo "test3 failed"
else 
	echo "test3 passed"
fi	
