#!/bin/bash

javac NoRepeat.java
#test1
java NoRepeat "abcdabd" > output

diff output test1.out
if [ $? -ne 0 ]; then
	echo "test1 failed"
else 
	echo "test1 passed"
fi
#test2
java NoRepeat "bbbb" > output
diff output test2.out
if [ $? -ne 0 ]; then
	echo "test2 failed"
else 
	echo "test2 passed"
fi	

#test3
java NoRepeat "pwwkew" > output
diff output test3.out
if [ $? -ne 0 ]; then
	echo "test3 failed"
else 
	echo "test3 passed"
fi

if [ 2 -eq 2 ]; then
	echo "test4 passed"
else
	echo "test4 failed"
fi

if [ 7 -lt 10 ]; then
	echo "test5 passed"
else
	echo "test5 failed"
fi

if [ 3 -eq 2 ]; then
	echo "test6 passed"
else
	echo "test6 failed"
fi
